### ISSUE TITLE
Style doesn't work with dark themes

### ISSUE THREAD

**Issue by nikkehtine** [Shad0wSeven/Quietfox-Proton#1]
Even with the solution listed in README.md, the stylesheet just doesn't want to work with any dark theme, also with visible artifacting on default dark theme.

![image](https://user-images.githubusercontent.com/27138416/143467500-cf8b5c6c-f9e3-4cfa-a93d-dcd405151686.png)
![image](https://user-images.githubusercontent.com/27138416/143466062-4d7321f0-3de5-4894-89fb-b639d3999199.png)
Theme on the screenshot: [Edge Dark](https://addons.mozilla.org/firefox/addon/edge-darkmode/)

**Comment by Shad0wSeven** [comment]
sorry for the late reply, I was out, but I'll try to fix this today.

**Comment by Shad0wSeven** [comment]
quick update, I fixed (I think) all the issues with tabs and the url, for both dark and light mode, although I'm working on the popout for the URL right now, I'm probably going to fix the popout issue tomorrow. Thanks for checking out my theme though! Hopefully I can make feature parity for both dark and light mode users soon!

![image](https://user-images.githubusercontent.com/19739712/143723376-8633f10c-d804-43c3-ab93-0c7fb9c232d6.png)


![image](https://user-images.githubusercontent.com/19739712/143723367-074c3c86-621a-4740-b7a9-62e73da65b5d.png)

**Comment by Shad0wSeven** [comment]
Okay I ended up fixing the problem, but there's one visual artifact that I can't find out how to fix, and but the rest should be fine

![image](https://user-images.githubusercontent.com/19739712/143723744-e75f748e-8f19-467f-afc7-63b67c698d6e.png)
On Edge Theme

![image](https://user-images.githubusercontent.com/19739712/143723751-734cee36-2a0b-4f0e-9e9b-d8e953033c1f.png)

Visual Artifacting on certain themes (not edge theme)

![image](https://user-images.githubusercontent.com/19739712/143723767-bf33739a-5e5e-4fe4-a2ca-11af30dece45.png)

Transparent Theme issues with URL

![image](https://user-images.githubusercontent.com/19739712/143723778-dec7a64d-97d3-4171-9fd1-ab6bde09f4ad.png)


I released this newer version under prerelease, until I can fix the issues with the tiny artifacts on some themes if you want to check it out and tell me if it fixes the issues on your system @nikkehtine 

If it works I'll close this issue, I've already opened another one for the tiny artifacts.

**Comment by nikkehtine** [comment]
Thank you for the response and time you dedicated for this fix. The issue seems to be fixed now, other than the artifacts you mentioned.
![image](https://user-images.githubusercontent.com/27138416/144087795-5b259fa6-c47d-40b6-a555-e2f1ebd45a81.png)
